language: python
sudo: false
cache:
- pip
python:
- '3.4'
- '3.5'
- '3.6'
addons:
  apt:
    packages:
    - pandoc
install:
- pip install -r requirements.txt
- pip install -U codecov pytest-gitignore pytest-pep8 pypandoc
script:
- coverage run --source pystart -m pytest
- python setup.py install
after_success:
- codecov
notifications:
  email:
    recipients:
      - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: Z8E4eHDFh1aZrVXr+KTyKscVcTbLP5r5IGWJYyGa4g3uxv+NKvduOBH0F2LKVj+di2WqxEnQIIDp2bIHKx1/zSY4wYdTluF2N8lPR+m54BaHus9BA6ZRSLgZMNZInkgzAEPlBwdge/I5GaEvflNgPUPs0mY3cfU0jmd8CdDDpF3G549IZTkuSMPBaqoDQaPkCdfQmnugp0Xc/t4HVbbu3e48r2DdPdkuhPyJBghfN51qDdAI6tSgefpFkSuhRe7HLtO8Pjk3N99I/Gn697cwUu/TcajPt3Kw82cYqCu0RpUSt2BeovXRl/c3+ua+7efPExvLKBOTZZ6gEtAzNpe0h0NUGWxP4cJYsMk1rY5xrqKTCIun0k3z8cXFWOrCxN5PUTAWdd9R5ATgwue2RI9hErgaLnItVM+fEDbLT8PJUs8RHYf+udCIjC79m1yBT/dMTJRUZaY5YZyxSec9j/U4vxDBIM5N/gohuaZJ+LJntGJ/Adso/vwvDp19dOx61G4diSdK0Hz/kot4+E4lvoWFhGBet1uQuSdU2aWdC1JJ20aSe9h33PGx886cXYQal9mE4SAmX1qAphSOsDQSzX4BwSC1op5IdLpN7HcbcjNPC4tLHn6Vmi5Ifq3eDtaahDzo9BouUzgcnu7u5inckE7JinoO/BO/Z1Sdicb0jtdjly8=
  on:
    tags: true
    repo: horta/pystart
    banch: master
